### ISSUE TITLE
How to use webjar for typescript to compile .ts files to .js

### ISSUE THREAD

**Issue by Kiran-N** [webjars/typescript#9]
I am using webjars for angular 2 , I want to compile my .ts to .js files, currently I am using tsc -w to compile the .ts files to .js. How to use this webjar for typescript to do the same.

**Comment by jamesward** [comment]
This depends on your build tool.  With sbt you can use a plugin: https://github.com/joost-de-vries/sbt-typescript

I'm not sure about other build tools.

**Comment by Kiran-N** [comment]
I am using Maven and eclipse

**Comment by jamesward** [comment]
It doesn't look like Maven has a TypeScript plugin that uses the WebJar.
